services:
  api:
    image: mlops-fastapi:v2
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: mlops
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mlops
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  mysql_data: